/** Shared hub settings tokens aligned with the neutral RiftApp grey theme. */
export const HS = {
  bgMain: '#15171a',
  bgSidebar: '#1f2125',
  bgHover: '#282b31',
  bgActive: '#32363e',
  bgCard: '#1f2125',
  border: '#2c2f36',
  borderSubtle: '#3a3f48',
  textPrimary: '#eceef2',
  textMuted: '#808791',
  textSecondary: '#b5bac1',
  textBody: '#eceef2',
  blurple: '#5865f2',
  blurpleHover: '#4752c4',
  linkBlue: '#00a8fc',
  danger: '#ed4245',
  dangerHover: '#f23f42',
  success: '#23a559',
  radius: '4px',
  radiusLg: '8px',
} as const;

export const hsTw = {
  main: 'bg-riftapp-content',
  sidebar: 'bg-riftapp-chrome',
  card: 'rounded-lg border border-riftapp-border/60 bg-riftapp-content-elevated',
  input: 'w-full rounded-[4px] bg-riftapp-content-elevated px-3 py-2.5 text-[15px] text-white border-none focus:outline-none focus:ring-1 focus:ring-[#5865f2]',
  btnPrimary: 'px-4 py-2 rounded-[4px] bg-[#5865f2] text-white text-[13px] font-medium hover:bg-[#4752c4] transition-colors disabled:opacity-40',
  btnDanger: 'px-4 py-2 rounded-[4px] border border-[#ed4245] text-[#ed4245] hover:bg-[#ed4245] hover:text-white text-[13px] font-medium transition-colors',
  title: 'text-[20px] font-bold text-white tracking-tight',
  subtitle: 'text-[13px] text-riftapp-text-muted leading-relaxed',
  sectionTitle: 'text-[12px] font-bold uppercase tracking-wider text-riftapp-text-muted',
  navCat: 'mt-1 mb-1.5 px-2.5 text-[11px] font-bold uppercase tracking-wider text-riftapp-text-dim',
} as const;
